//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.MeanChords.Data.Db.Context.DiscosChowell
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Disc()
        {
            this.DiscTag = new HashSet<DiscTag>();
            this.SaleDisc = new HashSet<SaleDisc>();
            this.ShoppingCar = new HashSet<ShoppingCar>();
        }
    
        public int DiscId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string DiscImgUrl { get; set; }
        public double Price { get; set; }
        public int Amount { get; set; }
        public bool Status { get; set; }
        public int AuthorId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
    
        public virtual Author Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscTag> DiscTag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleDisc> SaleDisc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCar> ShoppingCar { get; set; }
    }
}
